- hosts: terraform-ansible
  tasks:
    - name: criando arquivo
      copy:
        dest: /home/ubuntu/index.html
        content: <h1>Criado com Terraform e Ansible</h1>
    - name: criando servidor
      shell: "nohup busybox httpd -f -p 8080 &"